pipeline:
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/irs-990-loader
    tags: ${DRONE_COMMIT_SHA:0:12}
    when:
      event: [push, tag]
      branch: pachyderm

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/irs-990-loader
    release: irs-990-loader
    values: db.user=$${DB_USER},db.pass=$${DB_PASS},db.host=$${DB_HOST},db.name=$${DB_NAME},fec_key=$${FEC_KEY},image.repository=publicintegrity/irs-990-loader,image.tag=latest
    prefix: 
    namespace: irs-990-loader
    secrets: [ api_server, kubernetes_token, db_user, db_pass, db_host, db_name ]
    skip_tls_verify: true
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
