apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: "0 5 * * 1"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            buildID: {{ .Values.buildID }}
          labels:
            draft: {{ default "draft-app" .Values.draft }}
            app: {{ template "fullname" . }}
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  key:  db_name
                  name: {{ .Release.Name }}-auth
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  key:  db_user
                  name: {{ .Release.Name }}-auth
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  key:  db_pass
                  name: {{ .Release.Name }}-auth
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  key:  db_host
                  name: {{ .Release.Name }}-auth
            - name: "DB_DRIVER"
              valueFrom:
                secretKeyRef:
                  key:  db_driver
                  name: {{ .Release.Name }}-auth
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  key:  db_port
                  name: {{ .Release.Name }}-auth
            resources:
{{ toYaml .Values.resources | indent 16 }}
