---
pipeline:
  name: irs-990-electronic-filings-meta-append
transform:
  image: publicintegrity/irs-990-loader:1854f525e29a
  cmd:
  - bash
  stdin:
  - ./filings-meta/transforms/append.sh /pfs/download/ /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: download
    repo: irs-990-electronic-filings-meta-download
    glob: /*
    lazy: true
