---
pipeline:
  name: irs-990-electronic-filings-meta-download
transform:
  image: publicintegrity/irs-990-loader
  cmd:
  - bash
  stdin:
  - ./filings-meta/transform/download.sh /pfs/irs-990-electronic-filings-meta-check /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
- pfs:
    name: irs-990-electronic-filings-meta-check
    glob: /*
    empty_files: true
