---
pipeline:
  name: irs-990-electronic-filings-meta-load
transform:
  image: publicintegrity/irs-990-loader:1854f525e29a
  cmd:
  - bash
  stdin:
  - ./filings-meta/transforms/load.sh /pfs/append/
  secrets:
    - name: pachyderm-postgres-politics-auth
      env_var: PGHOST
      key: pghost
    - name: pachyderm-postgres-politics-auth
      env_var: PGDATABASE
      key: pgdatabase
    - name: pachyderm-postgres-politics-auth
      env_var: PGUSER
      key: pguser
    - name: pachyderm-postgres-politics-auth
      env_var: PGPASSWORD
      key: pgpassword
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: append
    repo: irs-990-electronic-filings-meta-append
    glob: /*
    lazy: true
